--SCROLL Cursor in SQL Server

--FORWARD_ONLY/SCROLL/FAST_FORWARD (= STATIC+FORWARD_ONLY)

DECLARE EmpTab_CURSOR CURSOR 
SCROLL 
FOR SELECT * FROM EmpTab 

	OPEN EmpTab_CURSOR 

		FETCH NEXT FROM EmpTab_CURSOR 
		FETCH LAST FROM EmpTab_CURSOR 
		FETCH FIRST FROM EmpTab_CURSOR 
		FETCH ABSOLUTE 5  FROM EmpTab_CURSOR 
		FETCH RELATIVE 3 FROM EmpTab_CURSOR 
		FETCH PRIOR FROM EmpTab_CURSOR 
		FETCH RELATIVE -3 FROM EmpTab_CURSOR 

	CLOSE EmpTab_CURSOR 

DEALLOCATE EmpTab_CURSOR 
