--FORWARD_ONLY Cursor in SQL Server

--FORWARD_ONLY/SCROLL/FAST_FORWARD

DECLARE EmpTab_CURSOR CURSOR 
FORWARD_ONLY 
FOR SELECT * FROM EmpTab 

	OPEN EmpTab_CURSOR 

		FETCH NEXT FROM EmpTab_CURSOR 
		FETCH NEXT FROM EmpTab_CURSOR 
		FETCH NEXT FROM EmpTab_CURSOR 
		FETCH NEXT FROM EmpTab_CURSOR 
		FETCH NEXT FROM EmpTab_CURSOR 

	
	CLOSE EmpTab_CURSOR 

DEALLOCATE EmpTab_CURSOR 
